version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"

    volumes:
      - ./:/usr/src/app:ro

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    env_file:
      - .env-docker-compose


  postgres:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=FastAPIComplete

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: